spring:
  application:
    name: mall-auth-server
  cloud:
    nacos:
      discovery:
        server-addr: 192.168.163.131:8848
  thymeleaf:
    cache: false
  redis:
    port: 6379
    host: 192.168.163.131

server:
  port: 20000
